### ISSUE TITLE
FUTO Voice Input not available as a default

### ISSUE THREAD

**Issue by IgorEisberg** [futo-org/voice-input#75] opened 2024-07-06 12:02 UTC
Hey guys, seems like there's a misconfiguration in AndroidManifest.xml in FUTO Voice Input app.
The app is not listed as an option for a default Voice Input handler.
Using Xiaomi 12 HyperOS 1.0.

![Screenshot_2024-07-06-14-57-44-998_com android settings](https://github.com/futo-org/voice-input/assets/8811086/6552a56f-28ed-44f9-8327-b659a8c38977)

**Comment by IgorEisberg** [comment] 2024-07-06 12:10
Looks like your "android.speech.RecognitionService" service points to a "DummyService" with the category set to "android.intent.category.TEST" instead of "android.intent.category.DEFAULT". No wonder it's not listed. :o

**Comment by abb128** [comment] 2024-07-06 23:33
Duplicate of #32

In short, most apps don't use the recognition service and instead use the intent since it's simpler to work with. So the recognition service isn't implemented in FUTO Voice Input.

The dummy service with TEST category is there just so that the app matches query filters from some other keyboard apps. It was purposefully made so it wouldn't show up in the picker, since the interface is left unimplemented

**Closed by abb128** 2024-07-06 23:33 UTC
